### ISSUE TITLE
The book is stable now (2.0)

### ISSUE THREAD

**Issue by bebraw** [survivejs-translations/webpack-book-zh#1]
Hi,

Just thought to let you know the book is stable. I had to make a lot of smaller edits to push quality of the final release. I hope that doesn't lead to too much work for you.

Is it easier if I invite you to my personal Slack?

--
Juho

**Comment by BingBlog** [comment]
Yeah, I have noticed that. We decide to finish the 1.8.7 and then  we will get the 2.0 done.

**Comment by bebraw** [comment]
Ok, cool. I think I'll close this then. Thanks. 👍

**Comment by BingBlog** [comment]
Here is my E-mail: phpzealer@163.com , can you invite me to you Slack? I just download the app.

**Comment by bebraw** [comment]
@BingBlog Done.
